[project]
name = "infer-csv-schema-python-tool"
version = "0.1.0"
description = "Use python, pandas, and pandera to infer a CSV schema"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pandas>=2.3.1", "pandera>=0.25.0"]
